name: NFS Server (Ganesha)
version: "1.0.0"
slug: nfs_ganesha
description: Expose Home Assistant folders via NFS using nfs-ganesha
url: https://github.com/sam-ward/nfs-ganesha-addon
startup: system
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
init: false
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - addon_configs:rw
  - backup:rw
  - share:rw
  - media:rw
host_network: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
apparmor: false
options:
  authorized_ips:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  export_folders:
    - config
    - ssl
    - addons
    - addon_configs
    - backup
    - share
    - media
schema:
  authorized_ips:
    - str
  export_folders:
    - match(config|ssl|addons|addon_configs|backup|share|media)
